<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

namespace CircleLinkHealth\Customer\Database\Seeders;

use CircleLinkHealth\Customer\Entities\Permission;
use CircleLinkHealth\Customer\Entities\Role;
use Illuminate\Database\Seeder;

class RequiredRolesPermissionsSeeder extends Seeder
{
    /**
     * Grant CLH Super Admin permissions to a Role, after you make sure you know what you are doing :).
     *
     * @param $roleName
     */
    public function grantSuperAdminPermissionsToRole($roleName)
    {
        $adminRole = Role::whereName($roleName)->first();

        $permissions = Permission::whereNotIn('name', $this->doNotGrantThesePermissionsToSuperAdmins())
            ->get();

        $adminRole->perms()->sync($permissions->pluck('id')->all());
    }

    public function roles()
    {
        return [
            [
                'name'         => 'administrator',
                'display_name' => 'CLH Super Admin',
                'description'  => 'Admins can see and do it all. Only CLH employees can have this Role.',
                'permissions'  => [],
            ],
            [
                'name'         => 'participant',
                'display_name' => 'Participant',
                'description'  => 'A patient at a practice.',
                'permissions'  => [
                    'users-view-self',
                    'patient.read',
                    'activity.read',
                    'note.read',
                    'appointment.read',
                    'provider.read',
                    'careplan-pdf.create',
                    'observation.create',
                    'observation.update',
                    'observation.read',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'api-ccd-vendor',
                'display_name' => 'API CCD Vendor',
                'description'  => 'Is able to post CCDs to our API',
                'permissions'  => [
                    'post-ccd-to-api',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.read',
                    'note.read',
                    'activity.read',
                    'location.read',
                    'practice.read',
                    'careplan-pdf.create',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'api-data-consumer',
                'display_name' => 'API Data Consumer',
                'description'  => 'Is able to receive PDF Reports and CCM Time from our API',
                'permissions'  => [
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.read',
                    'note.read',
                    'activity.read',
                    'location.read',
                    'practice.read',
                    'careplan-pdf.create',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'viewer',
                'display_name' => 'Viewer',
                'description'  => '',
                'permissions'  => [
                    'users-view-all',
                    'users-view-self',
                    'user.read',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'careplan.read',
                    'provider.read',
                    'activity.read',
                    'location.read',
                    'practice.read',
                    'activity.read',
                    'biometric.read',
                    'biometric.update',
                    'medication.read',
                    'medication.update',
                    'note.read',
                    'appointment.read',
                    'patientProblem.read',
                    'misc.read',
                    'observation.read',
                    'patientSummary.read',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'carePerson.read',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'office_admin',
                'display_name' => 'Office Admin',
                'description'  => 'Non medical staff that work at a Practice. Not CCM countable.',
                'permissions'  => [
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'patientProblem.create',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.delete',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'misc.create',
                    'misc.read',
                    'misc.update',
                    'misc.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'users-view-all',
                    'users-view-self',
                    'user.read',
                    'user.create',
                    'user.update',
                    'patient.read',
                    'patient.update',
                    'careplan.read',
                    'careplan.update',
                    'provider.read',
                    'note.create',
                    'note.read',
                    'note.update',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'location.read',
                    'practice.read',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'medication.read',
                    'medication.update',
                    'patientProblem.read',
                    'patientProblem.update',
                    'provider.read',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'nurse.read',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'patient.create',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'role.read',
                    'offlineActivity.create',
                    'change-patient-enrollment-status',
                    'vitals-survey-complete',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'no-ccm-care-center',
                'display_name' => 'Non CCM Care Center',
                'description'  => 'Care Center',
                'permissions'  => [
                    'ccd-import',
                    'post-ccd-to-api',
                    'users-edit-self',
                    'users-view-all',
                    'users-view-self',
                    'note.create',
                    'note.read',
                    'note.update',
                    'call.create',
                    'call.read',
                    'call.update',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'user.create',
                    'user.read',
                    'user.update',
                    'appConfig.create',
                    'appConfig.read',
                    'appConfig.update',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'role.read',
                    'role.update',
                    'practice.read',
                    'practice.update',
                    'permission.read',
                    'permission.update',
                    'careplan.read',
                    'careplan.update',
                    'location.create',
                    'location.read',
                    'location.update',
                    'provider.read',
                    'provider.update',
                    'biometric.read',
                    'biometric.update',
                    'medication.read',
                    'medication.update',
                    'patientProblem.read',
                    'patientProblem.update',
                    'misc.read',
                    'misc.update',
                    'patientSummary.read',
                    'patientSummary.update',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'carePerson.read',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'no-access',
                'display_name' => 'No Access',
                'description'  => '',
                'permissions'  => [],
            ],
            [
                'name'         => 'administrator-view-only',
                'display_name' => 'Administrator - View Only',
                'description'  => 'A special administrative account where you can view the admin but not perform actions',
                'permissions'  => [
                    'admin-access',
                    'users-edit-self',
                    'users-view-all',
                    'users-view-self',
                    'patient.read',
                    'patient.update',
                    'biometric.update',
                    'medication.update',
                    'careplan-pdf.create',
                    'note.read',
                    'call.read',
                    'activity.read',
                    'biometric.read',
                    'allergy.read',
                    'symptom.read',
                    'lifestyle.read',
                    'misc.read',
                    'appointment.read',
                    'provider.read',
                    'ccda.read',
                    'medication.read',
                    'patientProblem.read',
                    'instruction.read',
                    'observation.read',
                    'user.read',
                    'location.read',
                    'practice.read',
                    'nurse.read',
                    'role.read',
                    'practiceStaff.read',
                    'chargeableService.read',
                    'invite.read',
                    'enrollee.read',
                    'careplanAssessment.read',
                    'patientSummary.read',
                    'carePerson.read',
                    'careplan-pdf.read',
                    'workHours.read',
                    'emailSettings.read',
                    'addendum.read',
                    'batch.read',
                    'saas.read',
                    'ambassador.read',
                    'salesReport.read',
                    'ethnicityReport.read',
                    'opsReport.read',
                    'practiceInvoice.read',
                    'practiceInvoice.create',
                    'excelReport.read',
                    'excelReport.create',
                    'appConfig.read',
                    'family.read',
                    'permission.read',
                    'nurseInvoice.create',
                    'nurseInvoice.read',
                    'comment.read',
                    'nurseContactWindow.read',
                    'nurseHoliday.read',
                    'practiceSetting.read',
                    'medicationGroup.read',
                    'nurseReport.read',
                    'careplan.read',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'no-access',
                'display_name' => 'No Access',
                'description'  => '',
                'permissions'  => [],
            ],
            [
                'name'         => 'practice-lead',
                'display_name' => 'Program Lead',
                'description'  => 'The provider that created the practice.',
                'permissions'  => [
                    'users-view-all',
                    'users-view-self',
                    'call.create',
                    'call.read',
                    'call.update',
                    'call.delete',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.create',
                    'provider.read',
                    'provider.update',
                    'nurse.read',
                    'note.create',
                    'note.read',
                    'note.update',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'activity.delete',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'allergy.read',
                    'misc.read',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'patientProblem.create',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientSummary.read',
                    'patientSummary.update',
                    'chargeableService.read',
                    'chargeableService.update',
                    'careplan.create',
                    'careplan.read',
                    'careplan.update',
                    'location.create',
                    'location.read',
                    'location.update',
                    'practice.read',
                    'practice.update',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'comment.delete',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'registered-nurse',
                'display_name' => 'Registered Nurse',
                'description'  => 'A nurse that belongs to a practice and not our care center.',
                'permissions'  => [
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'patientProblem.create',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.delete',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'misc.create',
                    'misc.read',
                    'misc.update',
                    'misc.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'users-view-all',
                    'users-view-self',
                    'user.read',
                    'user.create',
                    'user.update',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'careplan.read',
                    'careplan.update',
                    'location.read',
                    'practice.read',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'provider.read',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'note.create',
                    'note.read',
                    'note.update',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'nurse.read',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'role.read',
                    'offlineActivity.create',
                    'vitals-survey-complete',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'specialist',
                'display_name' => 'Specialist',
                'description'  => 'An outside specialist doctor.',
                'permissions'  => [
                    'users-view-all',
                    'users-view-self',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.read',
                    'observation.create',
                    'observation.read',
                    'careplan.read',
                    'careplan.update',
                    'note.create',
                    'note.read',
                    'note.update',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'location.read',
                    'practice.read',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'medication.read',
                    'medication.update',
                    'patientProblem.read',
                    'misc.read',
                    'patientSummary.read',
                    'appointment.read',
                    'careplan-pdf.create',
                    'user.read',
                    'role.read',
                    'offlineActivity.create',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'salesperson',
                'display_name' => 'Salesperson',
                'description'  => 'A Salesperson',
                'permissions'  => [
                    'use-onboarding',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.read',
                    'note.read',
                    'activity.read',
                    'location.read',
                    'practice.read',
                    'careplan-pdf.create',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'care-ambassador',
                'display_name' => 'Care Ambassador',
                'description'  => 'People hired by CLH to call patients and enroll them to CarePlan Manager.',
                'permissions'  => [
                    'careplan.read',
                    'careplan.update',
                    'careplanAssessment.read',
                    'enrollee.read',
                    'enrollee.update',
                    'call.read',
                    'practice.read',
                    'provider.read',
                    'ambassador.read',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'care-ambassador-view-only',
                'display_name' => 'Care Ambassador - View Only',
                'description'  => 'Makes calls to enroll patients, and can see patient data for specific Practices',
                'permissions'  => [
                    'careplan.read',
                    'careplan.update',
                    'careplanAssessment.read',
                    'enrollee.read',
                    'enrollee.update',
                    'call.read',
                    'practice.read',
                    'provider.read',
                    'ambassador.read',
                    'patient.read',
                    'observation.read',
                    'note.read',
                    'activity.read',
                    'location.read',
                    'biometric.read',
                    'biomteric.update',
                    'medication.read',
                    'medication.update',
                    'patientProblem.read',
                    'misc.read',
                    'patientSummary.read',
                    'appointment.read',
                    'careplan-pdf.create',
                    'users-view-all',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'med_assistant',
                'display_name' => 'Medical Assistant',
                'description'  => 'Medical staff that work at a Practice, and are not Doctors or Registered Nurses. CCM Countable.',
                'permissions'  => [
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'patientProblem.create',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.delete',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'careplan-pdf.read',
                    'users-view-all',
                    'users-view-self',
                    'user.read',
                    'user.create',
                    'user.update',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'careplan.read',
                    'careplan.update',
                    'provider.read',
                    'note.create',
                    'note.read',
                    'note.update',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'location.read',
                    'practice.read',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'misc.read',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'careplan-pdf.create',
                    'misc.create',
                    'misc.read',
                    'misc.update',
                    'misc.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'nurse.read',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'role.read',
                    'offlineActivity.create',
                    'care-plan-approve',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'provider',
                'display_name' => 'Provider',
                'description'  => 'Doctors at a Practice.',
                'permissions'  => [
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'care-plan-approve',
                    'users-view-all',
                    'users-view-self',
                    'user.read',
                    'user.create',
                    'user.update',
                    'call.create',
                    'call.read',
                    'call.update',
                    'call.delete',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'provider.create',
                    'provider.read',
                    'provider.update',
                    'provider.delete',
                    'nurse.create',
                    'nurse.read',
                    'nurse.update',
                    'nurse.delete',
                    'note.create',
                    'note.read',
                    'note.update',
                    'note.delete',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'activity.delete',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'appointment.delete',
                    'misc.create',
                    'misc.read',
                    'misc.update',
                    'misc.delete',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'patientProblem.create',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'chargeableService.read',
                    'chargeableService.update',
                    'careplan.create',
                    'careplan.read',
                    'careplan.update',
                    'location.create',
                    'location.read',
                    'location.update',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'practice.read',
                    'practice.update',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'careplan-pdf.delete',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'comment.delete',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'note.send',
                    'role.read',
                    'offlineActivity.create',
                    'change-patient-enrollment-status',
                    'vitals-survey-complete',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'care-center',
                'display_name' => 'CLH Care Coach',
                'description'  => 'Care Coaches (Nurses) who work for CLH. They place calls to patients (participants) regularly. CCM/BHI countable.',
                'permissions'  => [
                    'legacy-bhi-consent-decision.create',
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'care-plan-rn-approve',
                    'users-view-all',
                    'users-view-self',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'user.create',
                    'user.read',
                    'user.update',
                    'careplan.read',
                    'careplan.update',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.create',
                    'patientProblem.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'misc.read',
                    'misc.create',
                    'misc.update',
                    'misc.delete',
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'appointment.delete',
                    'provider.read',
                    'practice.read',
                    'note.create',
                    'note.read',
                    'note.update',
                    'note.delete',
                    'call.create',
                    'call.read',
                    'call.update',
                    'call.delete',
                    'ccd-import',
                    'location.read',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'role.read',
                    'permission.read',
                    'nurseContactWindow.create',
                    'nurseContactWindow.read',
                    'nurseContactWindow.update',
                    'nurseContactWindow.delete',
                    'nurseHoliday.create',
                    'nurseHoliday.read',
                    'nurseHoliday.update',
                    'nurseHoliday.delete',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'nurse.read',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'workHours.create',
                    'workHours.update',
                    'workHours.delete',
                    'workHours.read',
                    'note.send',
                    'offlineActivityRequest.create',
                    'offlineActivityRequest.read',
                    'has-schedule',
                    'change-patient-enrollment-status',
                    'vitals-survey-complete',
                    'phi.read',
                    'attestedProblems.create',
                    'attestedProblems.read',
                    'attestedProblems.update',
                    'phoneNumber.create',
                    'phoneNumber.update',
                    'phoneNumber.delete',
                    'phoneNumber.read',
                ],
            ],
            [
                'name'         => 'care-center-external',
                'display_name' => 'Care Coach',
                'description'  => 'Care Coaches (Nurses) not employed by CLH. They place calls to patients (participants) regularly. CCM/BHI countable.',
                'permissions'  => [
                    'legacy-bhi-consent-decision.create',
                    'allergy.create',
                    'allergy.read',
                    'allergy.update',
                    'allergy.delete',
                    'care-plan-rn-approve',
                    'users-view-all',
                    'users-view-self',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'user.create',
                    'user.read',
                    'user.update',
                    'careplan.read',
                    'careplan.update',
                    'biometric.create',
                    'biometric.read',
                    'biometric.update',
                    'biometric.delete',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.create',
                    'patientProblem.delete',
                    'patientSummary.read',
                    'patientSummary.update',
                    'misc.read',
                    'misc.create',
                    'misc.update',
                    'misc.delete',
                    'medication.create',
                    'medication.read',
                    'medication.update',
                    'medication.delete',
                    'activity.create',
                    'activity.read',
                    'activity.update',
                    'appointment.create',
                    'appointment.read',
                    'appointment.update',
                    'appointment.delete',
                    'provider.read',
                    'practice.read',
                    'note.create',
                    'note.read',
                    'note.update',
                    'note.delete',
                    'call.create',
                    'call.read',
                    'call.update',
                    'call.delete',
                    'ccd-import',
                    'location.read',
                    'observation.create',
                    'observation.read',
                    'observation.update',
                    'observation.delete',
                    'instruction.create',
                    'instruction.read',
                    'instruction.update',
                    'instruction.delete',
                    'role.read',
                    'permission.read',
                    'nurseContactWindow.create',
                    'nurseContactWindow.read',
                    'nurseContactWindow.update',
                    'nurseContactWindow.delete',
                    'nurseHoliday.create',
                    'nurseHoliday.read',
                    'nurseHoliday.update',
                    'nurseHoliday.delete',
                    'careplan-pdf.create',
                    'careplan-pdf.read',
                    'careplan-pdf.update',
                    'carePerson.read',
                    'carePerson.create',
                    'carePerson.update',
                    'carePerson.delete',
                    'symptom.create',
                    'symptom.read',
                    'symptom.update',
                    'symptom.delete',
                    'medicationGroup.create',
                    'medicationGroup.read',
                    'medicationGroup.update',
                    'medicationGroup.delete',
                    'lifestyle.create',
                    'lifestyle.read',
                    'lifestyle.update',
                    'lifestyle.delete',
                    'comment.create',
                    'comment.read',
                    'comment.update',
                    'careplanAssessment.read',
                    'careplanAssessment.create',
                    'careplanAssessment.update',
                    'careplanAssessment.delete',
                    'nurse.read',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'workHours.create',
                    'workHours.update',
                    'workHours.delete',
                    'workHours.read',
                    'note.send',
                    'offlineActivityRequest.create',
                    'offlineActivityRequest.read',
                    'has-schedule',
                    'vitals-survey-complete',
                    'phi.read',
                    'phoneNumber.create',
                    'phoneNumber.update',
                    'phoneNumber.delete',
                    'phoneNumber.read',
                ],
            ],
            [
                'name'         => 'ehr-report-writer',
                'display_name' => 'EHR Report Writer',
                'description'  => 'A user that can upload CSVs or Json files for eligibility to be processed by our system',
                'permissions'  => [
                    'ehr-report-writer-access',
                ],
            ],
            [
                'name'         => 'saas-admin',
                'display_name' => 'SAAS Admin',
                'description'  => 'An admin for CPM Software-As-A-Service.',
                'permissions'  => [
                ],
            ],
            [
                'name'         => 'saas-admin-view-only',
                'display_name' => 'Saas Admin - View Only',
                'description'  => 'Created for MDAlly, a partner which white-labels our CCM service to their customers',
                'permissions'  => [
                    'admin-access',
                    'users-edit-self',
                    'users-view-all',
                    'users-view-self',
                    'patient.create',
                    'patient.read',
                    'patient.update',
                    'patient.delete',
                    'biometric.update',
                    'medication.update',
                    'careplan-pdf.create',
                    'note.read',
                    'call.read',
                    'activity.read',
                    'biometric.read',
                    'allergy.read',
                    'symptom.read',
                    'lifestyle.read',
                    'misc.read',
                    'appointment.read',
                    'provider.create',
                    'provider.read',
                    'provider.update',
                    'provider.delete',
                    'ccda.read',
                    'medication.read',
                    'patientProblem.read',
                    'instruction.read',
                    'observation.read',
                    'user.create',
                    'user.read',
                    'user.update',
                    'user.delete',
                    'location.read',
                    'practice.create',
                    'practice.read',
                    'practice.update',
                    'practice.delete',
                    'nurse.create',
                    'nurse.read',
                    'nurse.update',
                    'nurse.delete',
                    'role.read',
                    'practiceStaff.create',
                    'practiceStaff.read',
                    'practiceStaff.update',
                    'practiceStaff.delete',
                    'chargeableService.read',
                    'invite.read',
                    'enrollee.read',
                    'careplanAssessment.read',
                    'patientSummary.read',
                    'carePerson.create',
                    'carePerson.read',
                    'carePerson.update',
                    'carePerson.delete',
                    'careplan-pdf.read',
                    'workHours.read',
                    'emailSettings.create',
                    'emailSettings.read',
                    'emailSettings.update',
                    'emailSettings.delete',
                    'addendum.create',
                    'addendum.update',
                    'addendum.delete',
                    'addendum.read',
                    'batch.read',
                    'saas.create',
                    'saas.read',
                    'saas.update',
                    'saas.delete',
                    'ambassador.create',
                    'ambassador.read',
                    'ambassador.update',
                    'ambassador.delete',
                    'salesReport.read',
                    'ethnicityReport.read',
                    'opsReport.read',
                    'practiceInvoice.read',
                    'practiceInvoice.create',
                    'practiceInvoice.update',
                    'practiceInvoice.delete',
                    'excelReport.read',
                    'excelReport.create',
                    'appConfig.read',
                    'family.read',
                    'permission.read',
                    'nurseInvoice.create',
                    'nurseInvoice.read',
                    'comment.read',
                    'nurseContactWindow.read',
                    'nurseHoliday.read',
                    'practiceSetting.create',
                    'practiceSetting.read',
                    'practiceSetting.update',
                    'practiceSetting.delete',
                    'medicationGroup.read',
                    'ccd-import',
                    'use-onboarding',
                    'nurseReport.read',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'software-only',
                'display_name' => 'CCM Admin',
                'description'  => 'Uses only the software solution of CLH (CPM)',
                'permissions'  => [
                    'practice-admin',
                    'patientSummary.read',
                    'patientSummary.create',
                    'patientSummary.update',
                    'patientProblem.read',
                    'patientProblem.update',
                    'patientProblem.delete',
                    'chargeableService.read',
                    'practice.read',
                    'call.read',
                    'call.create',
                    'call.update',
                    'call.delete',
                    'phi.read',
                ],
            ],
            [
                'name'         => 'developer',
                'display_name' => 'CLH Developer',
                'description'  => 'Access to Horizon and Ops report. Access to PHI is forbidden.',
                'permissions'  => [
                    'opsReport.read',
                    'nurseReport.read',
                ],
            ],

            [
                'name'         => 'survey-only',
                'display_name' => 'Survey User',
                'description'  => 'Became Users just to be enrolled in AWV survey',
                'permissions'  => [
                    'phi.read',
                ],
            ],
        ];
    }

    /**
     * Run the database seeds.
     *
     * Seeds only default permissions for roles
     */
    public function run()
    {
        $this->call(RequiredPermissionsTableSeeder::class);

        foreach ($this->roles() as $role) {
            $permissionsArr = $role['permissions'];

            unset($role['permissions']);

            $role = Role::updateOrCreate(['name' => $role['name']], $role);

            $permissionIds = Permission::whereIn('name', $permissionsArr)
                ->pluck('id')->all();

            $role->perms()->sync($permissionIds);

            $name = $role['name'];
            $this->command->info("role ${name} created");
        }

        $this->grantSuperAdminPermissionsToRole('administrator');
        $this->grantSuperAdminPermissionsToRole('saas-admin');

        $this->command->info('all roles and permissions created');
    }

    /**
     * These are the only permissions tha will not be granted to Users with Role `administrator` (CLH Super Admin).
     *
     * @return array
     */
    private function doNotGrantThesePermissionsToSuperAdmins()
    {
        return [
            'care-plan-approve',
        ];
    }
}
