@extends('layouts.app')
@section('content')
    <send-assessment-link
            :patient-id="{{json_encode($patientId)}}"
            :patient-name="{{json_encode($patientName)}}"
            :survey-name="{{json_encode($surveyName)}}"
            :via="{{json_encode($via)}}"
    ></send-assessment-link>
@endsection
