<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

namespace CircleLinkHealth\Customer\Helpers;

use Illuminate\Support\Str;

/**
 * Verifies whether emails where generated by CLH.
 *
 * Context:
 * If Enrollees do not have emails, CPM will generate a fake email using formula: "e{$enrollee->id}@careplanmanager.com"
 *
 * Class PlaceholderEmailsVerifier
 */
class PlaceholderEmailsVerifier
{
    /**
     * Fake email generated for enrollees without email.
     */
    const CLH_GENERATED_EMAIL_DOMAIN = '@careplanmanager.com';

    /**
     * Returns true if the given email has been generated by CLH.
     */
    public static function isClhGeneratedEmail(?string $email): bool
    {
        return Str::contains($email, self::CLH_GENERATED_EMAIL_DOMAIN);
    }
}
