<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Enrollable extends JsonResource
{
    public function toArray($request)
    {
        $x = 1;

        return $this; // TODO: Change the autogenerated stub
    }
}
