pull_request_rules:
  - name: automatic merge on CI success and 2 reviews
    conditions:
      - status-success=ci/circleci
      - "#approved-reviews-by>=2"
      - base=development
    actions:
      merge:
        method: merge
        strict: true
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}