pull_request_rules:
- name: automatic merge on CI success and 2 reviews
  conditions:
  - status-success=ci/circleci
  - "#approved-reviews-by>=2"
  - "#changes-requested-reviews-by=0"
  - label!=wip
  - base=development
  - base!=master
  - head!=master
  actions:
    merge:
      method: merge
      strict: smart
- name: delete head branch after merge
  conditions: []
  actions:
    delete_head_branch: {}
- name: remove outdated reviews
  conditions:
  - base=development
  actions:
    dismiss_reviews: {}