# docker-compose.yml #
version: "3.7"
services:

  # laravel app
  app:
    image: cpm-web
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USERNAME=root
      - DB_HOST=mysql
      - DB_PORT=30061
      - DB_DATABASE=cpm_tests
      - DB_PASSWORD=secret
    ports:
      - "8080:8080"
      - "443:443"
    restart: unless-stopped

  # mysql db
  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network
    ports:
      - "30061:3306"
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis
    ports:
      - "63781:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisData:/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  redisData:
    driver: local