# docker-compose.yml #
version: "3.7"
services:
  app:
    volumes:
    - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
    - 8000:8000
    build:
      context: docker/php
      dockerfile: dev.Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  mysql:
    image: mysql:5.7.28
    restart: unless-stopped
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
    - "33060:3306"
    volumes:
    - "mysql-data:/var/lib/mysql:rw"
volumes:
  mysql-data: {}