# docker-compose.yml #
version: "3.7"
services:

  # laravel app
  app:
    image: cpm-web
    depends_on:
    - mysql
    - redis
    networks:
    - app-network
    environment:
      - PORT=8080
      - CACHE_DRIVER=array
      - SESSION_DRIVER=array
    ports:
      - "8080:8080"
      - "443:443"
    restart: unless-stopped
    volumes:
    - .:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # mysql db
  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
    - app-network
    ports:
    - "33066:3306"
    restart: unless-stopped
    volumes:
    - dbdata:/var/lib/mysql
    - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
    - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local