# docker-compose.yml #
version: "3.7"
services:

  # laravel app
  app:
    build:
      context: docker/php
      dockerfile: dev.Dockerfile
    container_name: app
    depends_on:
    - mysql
    networks:
    - app-network
    restart: unless-stopped
    tty: true
    volumes:
    - .:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www

  # mysql db
  mysql:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    image: mysql:5.7.28
    networks:
    - app-network
    ports:
    - "33060:3306"
    restart: unless-stopped
    volumes:
    - dbdata:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis
    networks:
    - app-network

  # nginx webserver
  web:
    depends_on:
    - app
    image: nginx:1.17.5
    networks:
    - app-network
    ports:
    - "8085:80"
    - "443:443"
    volumes:
    - ./docker/web/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local