#!/bin/bash
################################################################################
#
# Bash PHP Coding Standards Fixer
#
# This will prevent a commit if the tool has made changes to the files. This
# allows a develop to look at the diff and make changes before doing the
# commit.
#
# Exit 0 if no errors found
# Exit 1 if errors were found
#
# Requires
# - php#
# Arguments
# - Nonq.w-,eœ
#
###########################################################################q.w-,e

# Plugin title
title="PHP Code Fixer"

# Possible command names of this tool
local_command="php-cs-fixer.phar"
vendor_command="vendor/bin/php-cs-fixer"
global_command="php-cs-fixer"

# Print a welcome and locate the exec for this tool
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/helpers/colors.sh
source $DIR/helpers/formatters.sh
source $DIR/helpers/welcome.sh
source $DIR/helpers/locate.sh

# Get modified files, staged for commit
declare -a CHANGED_FILES=$(git diff-index HEAD --name-only | grep ".php")

printf '%s\n' "${CHANGED_FILES}"

args="--verbose --show-progress=dots --diff --path-mode=override"
php_errors_found=false
error_message=""

# Run the command on each file
for path in "${CHANGED_FILES[@]}"
do
    echo "checking ${path}"

    add_file_again=0

    if [[ ${path} == *"resources/views/"* ]]; then
        echo "php view file"

        echo "$exec_command fix $path --config=.php_cs_views.php $args"

        ${exec_command} fix ${path} --config=.php_cs_views.php ${args}

        add_file_again=1
    elif [[ ${path} == *".php"* ]]; then
        echo "php file"
        echo "$exec_command fix $path --config=.php_cs.dist $args"

        ${exec_command} fix ${path} --config=.php_cs.dist ${args}

        add_file_again=1
    else
        echo "non-php file"
    fi

    if [ $? -ne 0 ]; then
        echo "errors"
        error_message+="  - ${txtred}${path}${txtrst}\n"
        php_errors_found=true
     elif [[ $add_file_again == 1 ]]; then
        echo "re-adding $path"
        git add ${path}
        echo "😍"
    fi
done;

# There is currently debate about exit codes in php-cs-fixer
# https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1211
if [ "$php_errors_found" = true ]; then
    echo -en "\n${undred}${title} updated the following files:${txtrst}\n"
    echo -en "\n${error_message}"
    echo -en "\n${txtwht}${bakred}Please review the changes above. If you're happy, please commit and push.${txtrst}\n"
    exit 1
fi

echo "${txtgrn} All good! 😍 You may proceed to committing/pushing your code.${txtrst} \n"
exit 0
