#!/bin/bash

# composer test
# COMPOSER_TEST_EC=$?

npm test -- --silent
NPM_TEST_EC=$?

# let "ERROR = $COMPOSER_TEST_EC + $NPM_TEST_EC"
ERROR=$NPM_TEST_EC

if [ ${ERROR} -eq "0" ]
then
    echo "all good! 😍"
else
    echo "push aborted 👎 | error $ERROR"
    exit ${ERROR}
fi