#!/bin/sh


composer dumpautoload

COMPOSER_DUMP_AUTOLOAD_EC=$?

#echo 'Checking Javascript code quality...'
#jscs ./js
#JSCS_EC=$?

echo 'Checking PHP code style...'
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix app/ --rules=@PSR2 --show-progress=estimating --verbose --diff
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix config/ --rules=@PSR2 --show-progress=estimating --verbose --diff
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix database/ --rules=@PSR2 --show-progress=estimating --verbose --diff
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix resources/ --rules=@PSR2 --show-progress=estimating --verbose --diff
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix routes/ --rules=@PSR2 --show-progress=estimating --verbose --diff
php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix tests/ --rules=@PSR2 --show-progress=estimating --verbose --diff

# composer test
# COMPOSER_TEST_EC=$?

# npm test -- --silent
NPM_TEST_EC=$?

let "ERROR = $NPM_TEST_EC + $JSCS_EC + PHPCS_EC + $COMPOSER_DUMP_AUTOLOAD_EC"
# ERROR=$NPM_TEST_EC

if [ ${ERROR} -eq "0" ]
then
    echo "all good! 😍"
else
    echo "push aborted 👎 | error $ERROR"
    exit ${ERROR}
fi