#!/bin/sh

CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB)
EXTRA_ARGS="--path-mode=override"

while read -r line; do
    if [[ $line == *"resources/views/"* ]]
    then
        echo "running: php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix ${line} --config=.php_cs_views.php"
        php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix ${line} --config=.php_cs_views.php ${EXTRA_ARGS}
    elif [[ $line == *".php"* ]]
    then
        echo "running: php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix ${line} --config=.php_cs.dist"
        php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix ${line} --config=.php_cs.dist ${EXTRA_ARGS}
    else
        echo "No action with ${line}"
    fi
done <<< "$CHANGED_FILES"

ERROR=$?

if [ ${ERROR} -eq "0" ]
then
    echo "all good! 😍"
else
    echo "commit aborted 👎 | error $ERROR"
    exit ${ERROR}
fi