<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

use Illuminate\Database\Migrations\Migration;

class AwvVitalsQ4BmiAutoGenerated extends Migration
{
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $questionsTable      = 'questions';
        $questionGroupsTable = 'question_groups';

        DB::table($questionsTable)
            ->where('body', 'Word Recall (1 point for each word spontaneously recalled without cueing) 
                http://mini-cog.com/wp-content/uploads/2015/12/Universal-Mini-Cog-Form-011916.pdf')
            ->update(['body' => 'Word Recall (1 point for each word spontaneously recalled without cueing)']);

        DB::table($questionGroupsTable)
            ->where(
                'body',
                'Based off of the Mini-Cog(c) assessment, how did your patient score? (insert link)'
            )
            ->update(['body' => 'Based off of the Mini-Cog(c) assessment, how did your patient score? http://mini-cog.com/wp-content/uploads/2015/12/Universal-Mini-Cog-Form-011916.pdf']);

        DB::table($questionsTable)
            ->where('body', 'What is the patient\'s body mass index (BMI)?')
            ->update([
                'conditions' => json_encode([
                    'is_auto_generated' => true,
                    'generate_func'     => 'bmi_func',
                    'generated_from'    => [
                        [
                            'order' => 2,
                            'type'  => 'mass',
                        ],
                        [
                            'order' => 3,
                            'type'  => 'height',
                        ],
                    ],
                ]),
            ]);
    }
}
