# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # Specify the version you desire here
    - image: circleci/php:7.2-fpm-node-browsers-legacy

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # Using the RAM variation mitigates I/O contention
    # for database intensive operations.
    # - image: circleci/mysql:5.7-ram
    #
    - image: redis:2.8.19

    steps:
    - checkout

    - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libpng-dev
    - run: sudo docker-php-ext-install zip pcntl exif bcmath gd

    # Download and cache dependencies

    # composer cache
    - restore_cache:
        keys:
        # "composer.lock" can be used if it is committed to the repo
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n --prefer-dist

    - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
        - vendor

    # node cache

    - restore_cache:
        keys:
        - node-v3-{{ checksum "package.json" }}
        - node-v3-
    - run: npm install
    - save_cache:
        key: node-v3-{{ checksum "package.json" }}
        paths:
        - node_modules
        - ~/.yarn

    # gonna cache this at some point
    - run: npm run build-dev

    # prepare the database
    - run: cp .env.testing .env

      # run tests with paratest
    - run: composer unit-test
    - store_test_results:
        path: tests/_output
    - store_artifacts:
        path: tests/_output
    - run:
        name: Add a version to the build
        command: |
          php artisan version:refresh
          php artisan version:absorb
          git add config/version.yml
          git commit --allow-empty -m "Version build"
          git push