<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

namespace App\Helpers;

use Illuminate\Support\Str;

class PlaceholderEmailsVerifier
{
    /**
     * Fake email generated for enrollees without email.
     */
    const CLH_GENERATED_EMAIL_DOMAIN = '@careplanmanager.com';

    /**
     * Returns true if the given email has been generated by CLH.
     */
    public static function isClhGeneratedEmail(?string $email): bool
    {
        return Str::contains($email, self::CLH_GENERATED_EMAIL_DOMAIN);
    }
}
