<?php

namespace App;

class HraQuestionIdentifier
{
    const RACE = 'Q_RACE';
    const ETHNICITY = 'Q_ETHNICITY';
    const AGE = 'Q_AGE';
    const HEIGHT = 'Q_HEIGHT';
    const SEX = 'Q_SEX';
    const RATE_HEALTH = 'Q_RATE_HEALTH';
    const FRUIT = 'Q_FRUIT';
    const FIBER = 'Q_FIBER';
    const FATTY_FOOD = 'Q_FATTY_FOOD';
    const SUGAR = 'Q_SUGAR';
    const APPETITE = 'Q_APPETITE';
    const TOBACCO = 'Q_TOBACCO';
    const TOBACCO_YEARS = 'Q_TOBACCO_YEARS';
    const TOBACCO_LAST_TIME = 'Q_TOBACCO_LAST_TIME';
    const TOBACCO_PACKS = 'Q_TOBACCO_PACKS';
    const TOBACCO_QUIT = 'Q_TOBACCO_QUIT';
    const ALCOHOL = 'Q_ALCOHOL';
    const ALCOHOL_CONSUMPTION = 'Q_ALCOHOL_CONSUMPTION';
    const RECREATIONAL_DRUGS = 'Q_RECREATIONAL_DRUGS';
    const RECREATIONAL_DRUGS_WHICH = 'Q_RECREATIONAL_DRUGS_WHICH';
    const EXERCISE = 'Q_EXERCISE';
    const SEXUALLY_ACTIVE = 'Q_SEXUALLY_ACTIVE';
    const SEXUALLY_ACTIVE_PARTNERS = 'Q_SEXUALLY_ACTIVE_PARTNERS';
    const SEXUALLY_ACTIVE_SAFE = 'Q_SEXUALLY_ACTIVE_SAFE';
    const CONDITIONS = 'Q_CONDITIONS';
    const CONDITIONS_EXTRA = 'Q_CONDITIONS_EXTRA';
    const CONDITIONS_FAMILY = 'Q_CONDITIONS_FAMILY';
    const CONDITIONS_FAMILY_WHO = 'Q_CONDITIONS_FAMILY_WHO';
    const SURGERIES = 'Q_SURGERIES';
    const MEDICATION = 'Q_MEDICATION';
    const ALLERGIES = 'Q_ALLERGIES';
    const INTEREST_DOING_THINGS = 'Q_INTEREST_DOING_THINGS';
    const DEPRESSED = 'Q_DEPRESSED';
    const DIFFICULTIES = 'Q_DIFFICULTIES';
    const DIFFICULTIES_ASSISTANCE = 'Q_DIFFICULTIES_ASSISTANCE';
    const FALL_INCIDENT = 'Q_FALL_INCIDENT';
    const HEARING = 'Q_HEARING';
    const FLU_SHOT = 'Q_FLU_SHOT';
    const TDAP_VACCINATION = 'Q_TDAP_VACCINATION';
    const TETANUS_VACCINATION = 'Q_TETANUS_VACCINATION';
    const VARICELLA_VACCINATION = 'Q_VARICELLA_VACCINATION';
    const HEPATITIS_B_VACCINATION = 'Q_HEPATITIS_B_VACCINATION';
    const MEASLES_VACCINATION = 'Q_MEASLES_VACCINATION';
    const PAPILLOMAVIRUS_VACCINATION = 'Q_PAPILLOMAVIRUS_VACCINATION';
    const RZV_ZVL = 'Q_RZV_ZVL';
    const PCV13_PPSV23 = 'Q_PCV13_PPSV23';
    const MAMMOGRAM = 'Q_MAMMOGRAM';
    const PAP_SMEAR = 'Q_PAP_SMEAR';
    const COLORECTAR_CANCER = 'Q_COLORECTAR_CANCER';
    const SKIN_CANCER = 'Q_SKIN_CANCER';
    const PROSTATE_CANCER = 'Q_PROSTATE_CANCER';
    const GLAUCOMA = 'Q_GLAUCOMA';
    const OSTEOPOROSIS = 'Q_OSTEOPOROSIS';
    const INTIMATE_PARTNER_VIOLENCE = 'Q_INTIMATE_PARTNER_VIOLENCE';
    const PHYSICIANS = 'Q_PHYSICIANS';
    const MEDICAL_ATTORNEY = 'Q_MEDICAL_ATTORNEY';
    const LIVING_WILL = 'Q_LIVING_WILL';
    const LIVING_WILL_AT_DOCTOR = 'Q_LIVING_WILL_AT_DOCTOR';
    const COMMENTS = 'Q_COMMENTS';
}
