<template>
    <div>
        <div class="radio">
            <div>

                <template v-if="styleHorizontal">
                    <mdb-btn v-for="answer in possibleAnswers"
                             type="checkbox"
                             color="white"
                             size="sm"
                             :key="answer.id"
                             :active="answer.value === selectedAnswer"
                             :disabled="isAutoGenerated()"
                             @click="handleAnswer(answer.value)">
                        {{answer.value}}
                    </mdb-btn>
                </template>

                <template v-else>
                    <div v-for="answer in possibleAnswers">
                        <label>{{answer.value}}
                            <input :name="question.id"
                                   :value="answer.value"
                                   type="radio"
                                   @change="handleAnswer(answer.value)">
                        </label>
                    </div>
                </template>


                <div v-if="showDifferentInput"
                     v-for="input in differentInputTypesData">
                    <input id="different-input"
                           class="text-field"
                           name="textTypeAnswer"
                           v-model="inputHasText"
                           :placeholder="input.placeholder"
                           :type="input.type">
                </div>
            </div>

            <div v-if="isAutoGenerated()" :class="isLastQuestion ? 'text-center' : 'text-left'">
                <br>
                <mdbBtn v-show="isActive"
                        color="primary"
                        class="next-btn"
                        name="number"
                        id="number"
                        :disabled="nextButtonDisabled"
                        @click="handleAnswer()">
                    {{isLastQuestion ? 'Complete' : 'Next'}}
                </mdbBtn>
            </div>
        </div>
    </div>
</template>

<script>

    import {mdbBtn} from 'mdbvue';


    export default {
        name: "questionTypeRadio",
        props: ['question', 'userId', 'surveyInstanceId', 'isActive', 'isSubQuestion', 'onDoneFunc', 'styleHorizontal', 'getAllQuestionsFunc', 'isLastQuestion'],
        components: {mdbBtn},

        data() {
            return {
                selectedAnswer: null,
                nextButtonDisabled: false,
                possibleAnswers: [],
                questionOrder: this.question.pivot.order,
                questionOptions: [],
                differentInputTypesData: [],
                showDifferentInput: false,
                inputHasText: [],
            }
        },

        computed: {
            questionHasConditions() {
                return this.question.conditions != null;
            },

            hasOptions() {
                return this.questionOptions.length !== 0;
            },

            hasDifferentInputType() {
                if (this.hasOptions) {
                    const options = this.questionOptions.map(a => a.options);
                    return options[0].hasOwnProperty('answer_type') ? this.showDifferentInput = true : '';
                }
                return false;
            },

            /*answerIsYesOrNo() {


            },*/
        },


        methods: {
            handleAnswer(answerVal) {

                this.selectedAnswer = answerVal;

                const questionTypeAnswerId = this.possibleAnswers.filter(possibleAnswer => {
                    /*what i want to say is - if value === null*/
                    if (possibleAnswer.value !== answerVal) {
                        return possibleAnswer;
                    }
                    return possibleAnswer.value === answerVal;
                }).map(questionTypeAnswer => questionTypeAnswer.id);

                const answer = {
                    value: answerVal
                };

                this.onDoneFunc(this.question.id, answer)
                    .catch(err => {
                        //if there is error, app will not move to next question.
                        //handle it here
                    });
            },

            isAutoGenerated() {
                return this.question.conditions && this.question.conditions.is_auto_generated;
            }
        },

        created() {
            const questionOptions = this.question.type.question_type_answers.filter(question => question.options);
            this.questionOptions.push(...questionOptions);

            const possibleAnswers = this.question.type.question_type_answers.filter(possibleAnswer => possibleAnswer.value);
            this.possibleAnswers.push(...possibleAnswers);

            /*fetch input type & placeholder for the second input type*/
            if (this.hasDifferentInputType) {
                const inputTypeData = this.questionOptions.map(a => a.options);
                this.differentInputTypesData.push(...inputTypeData);
            }
        },

        mounted() {

        },

        watch: {
            isActive(newVal, oldVal) {

                if (newVal && this.isAutoGenerated()) {

                    let shouldDisableNextButton = false;
                    const conditions = this.question.conditions.generated_from;
                    const allQuestions = this.getAllQuestionsFunc();

                    //auto generated results assume integer values
                    let answer = 0;
                    conditions.forEach(c => {
                        const q = allQuestions.find(question => question.pivot.order === c.order && question.pivot.sub_order === c.sub_order);
                        if (q && q.answer) {
                            answer += parseInt(q.answer.value);
                        }
                        else {
                            shouldDisableNextButton = true;
                        }
                    });

                    this.nextButtonDisabled = shouldDisableNextButton;
                    this.selectedAnswer = answer.toString();
                }

            }
        }
    }
</script>

<style scoped>
    .radio label {
        width: 420px;
        height: 50px;
        border-radius: 5px;
        border: solid 1px #4aa5d2;
        background-color: #ffffff;
        margin-left: .5rem;
        padding-left: 3%;
        padding-top: 3%;
    }

    .radio label > text {
        padding-left: 3px;
    }

    .radio input[type="radio"] {
        /*  display: none;*/

    }

    .radio input[type="radio"]:checked + label {
        background-color: #4aa5d2;
    }

    .btn.btn-sm {
        font-size: 24px;
        width: 60px;
        height: 60px;
        border: solid 1px #4aa5d2;
        margin: 1px;
        padding: 0;
        box-shadow: none;
    }

    .btn.btn-sm.active {
        background-color: #50b2e2 !important;
        color: white;
    }
</style>
