<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class ChangeIsAutoGeneratedToBoolean extends Migration
{

    protected $tableName;
    protected $column = 'is_auto_generated';


    public function __construct()
    {
        $this->tableName = (new \App\User())->getTable();
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table($this->tableName, function (Blueprint $table) {
            if (Schema::hasColumn($this->tableName, $this->column)) {
                $table->dropColumn($this->column);
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table($this->tableName, function (Blueprint $table) {
            if (! Schema::hasColumn($this->tableName, $this->column)) {
                $table->boolean($this->column)
                    ->nullable()
                    ->default(null)
                    ->after('status');
            }
        });
    }

}
