<?php

/*
 * This file is part of CarePlan Manager by CircleLink Health.
 */

namespace App\Helpers;

use Illuminate\Support\Str;

class PlaceholderEmailsVerifier
{
    /**
     * Returns true if the given email has been generated by CLH.
     */
    public static function isClhGeneratedEmail(?string $email): bool
    {
        return Str::contains($email, [
            '@careplanmanager.com',
            '@example.com',
            '@noEmail.com',
            '@cpm.com',
            '@email.com',
        ]);
    }
}
