#!/bin/bash

#echo 'Checking Javascript code quality...'
#jscs ./js
#JSCS_EC=$?

#echo 'Checking PHP code style...'
# COMPOSER_MEMORY_LIMIT=-1 composer ide

#composer test
#COMPOSER_TEST_EC=$?

#npm test -- --silent
#NPM_TEST_EC=$?

#let "ERROR = $NPM_TEST_EC + $JSCS_EC + $COMPOSER_TEST_EC"
#ERROR=$NPM_TEST_EC

#if [ ${ERROR} -eq "0" ]
#then
#    echo "all good! 😍"
#else
#    echo "push aborted 👎 | error $ERROR"
#    exit ${ERROR}
#fi
