#!/bin/bash

BASEDIR=$(dirname "$BASH_SOURCE")

function copyHooksTo {
    SCRIPTS_DIR=$BASEDIR/git/
    echo "Copying GitHooks to "$1
    # copy git hooks to ./.git/hooks/ folder
    for FILE in $SCRIPTS_DIR/*;do
        if [ -d "$FILE" ]; then
            cp -R $FILE $1
        else
            install -m 755 "$FILE" $1
        fi
    done
}
copyHooksTo $BASEDIR/../.git/hooks/

{ find $BASEDIR/../Modules -maxdepth 1 -type d -exec printf '%s\0' {} + | while IFS= read -ru3 -d '' file; do
  copyHooksTo "$file"/.git/hooks/; done 3<&0 <&4 4<&-; } 4<&0