name: Deploy to Vapor
on:
  push:
  pull_request:
jobs:
  deploy:
    name: Vaporize
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/laravel-8.0' || github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Turnstyle - run workflow only once
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if commit message has [ci skip]
        uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - name: Install Composer dependencies
        uses: php-actions/composer@v5
        env:
          COMPOSER_MIRROR_PATH_REPOS: 1
        with:
          version: 1
          php_version: 7.4
          php_extensions: redis zip gd exif imagick opcache intl libxml pdo dom bcmath
          progress: yes
          dev: no
          args: --classmap-authoritative -vvv
      - name: Setup PHP - need this to run vapor deploy
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1
          extensions: redis, zip, gd, exif, imagick, opcache, intl, libxml, pdo, dom, bcmath
          coverage: none
      - name: Deploy
        run: ./vendor/bin/vapor deploy ${{ env.APP_ENV }} --commit="${{ github.sha }}"
        env:
          APP_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
