name: Deploy to Vapor
on:
  push:
  pull_request:
jobs:
  deploy:
    name: Deploy to Vapor
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/laravel-8.0' || github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if commit message has [ci skip]
        uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: redis, imagick, intl, json, simplexml

      - name: Validate Composer
        run: composer validate

      - name: Install Composer dependencies
        run: COMPOSER_MIRROR_PATH_REPOS=1 composer install --no-dev --classmap-authoritative -vvv

      - name: Deploy code
        run: ./vendor/bin/vapor deploy ${{ env.APP_ENV }} --commit="${{ github.sha }}"
        env:
          APP_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
